# Generated by Django 4.1 on 2022-08-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
