# Generated by Django 4.1 on 2022-08-20 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guitars', '0003_alter_guitars_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='guitars',
            options={'ordering': ['-published_time'], 'verbose_name_plural': 'Guitars'},
        ),
        migrations.AddField(
            model_name='guitars',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publication'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='category',
            field=models.ManyToManyField(to='guitars.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guitars',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
