# Generated by Django 4.1 on 2022-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_alter_category_options_alter_guitars_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitars',
            name='slug',
            field=models.SlugField(default=0, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
